/**
 * @typedef {string} mw.testKitchen.ContextualAttribute
 *
 * @package
 */

// ---

/**
 * @interface EventSenderInterface
 * @memberof mw.testKitchen
 */

/**
 * Sends the event to the URL using [the Beacon API][0].
 *
 * By default, the event is added to a queue, which is then drained after 5 seconds or if the
 * page is hidden, e.g. when the user switches to another tab. If the page is unloading,
 * however, the event will be sent immediately.
 *
 * When the queue is drained, events are grouped by URL and then those groups of events are sent
 * in a single beacon request to that URL.
 *
 * [0]: https://developer.mozilla.org/en-US/docs/Web/API/Beacon_API
 *
 * @method sendEvent
 * @instance
 * @memberof mw.testKitchen.EventSenderInterface
 *
 * @param {Object} event
 * @param {string} url
 */

// ---

// The relationship between PartialExperimentConfig and ExperimentConfig is different from
// that of PartialInstrumentConfig and InstrumentConfig. Currently, PartialExperimentConfig objects
// are looked up by stream name rather than experiment name. The relationship between the types
// reflects this.

/**
 * A partial configuration for an experiment, which was generated by
 * `\MediaWiki\Extension\TestKitchen\ResourceLoader\Hooks::getExperimentConfigs()`. This can be
 * removed as part of T408186.
 *
 * @typedef {Object} mw.testKitchen.PartialExperimentConfig
 * @property {mw.testKitchen.ContextualAttribute[]} contextual_attributes
 *
 * @package
 */

/**
 * @typedef {Object} mw.testKitchen.ExperimentConfig
 * @property {string} enrolled The machine-readable name of the experiment
 * @property {string} assigned The group assigned to the user
 * @property {string} subject_id The ID assigned to the user when they were enrolled in the
 *  experiment
 * @property {string} sampling_unit The sampling unit used to determine whether the user should
 *  be enrolled in the experiment
 * @property {string} coordinator The name of the system that coordinated the enrollment of the
 *  user in the experiment. This parameter is used as the value for the `experiment.coordinator`
 *  field in all experiment-related analytics events, so it should be one of `default`, `custom`, or
 *  `forced`
 * @property {string} stream_name The name of the stream to send experiment-related analytics
 *  events to
 * @property {string} schema_id The ID of the schema used to validate experiment-related analytics
 *  events with
 * @property {mw.testKitchen.ContextualAttribute[]} contextual_attributes
 * @property {Object<string,string>} other_assigned Enrollment information for all other experiments
 *  that the user is enrolled in expressed as a map of experiment name (enrolled) to group
 *  (assigned). This parameter is used as the value for the `experiment.other_assigned` field in all
 *  experiment-related analytics events. It is defined [here](https://gitlab.wikimedia.org/repos/data-engineering/schemas-event-secondary/-/blame/201ad8db1c4b7a0250646bfaf04817458728d8ed/jsonschema/fragment/analytics/product_metrics/experiment/latest.yaml#L35).
 *
 * @package
 */

// ---

/**
 * @interface ExperimentInterface
 * @memberof mw.testKitchen
 */

/**
 * Gets the group assigned to the user when they were enrolled in the experiment.
 *
 * @method getAssignedGroup
 * @instance
 * @memberof mw.testKitchen.ExperimentInterface
 *
 * @return {string|null}
 */

/**
 * Gets whether the group assigned to the current user is one of the given groups.
 *
 * @see mw.testKitchen.ExperimentInterface#getAssignedGroup
 *
 * @example
 * const e = mw.testKitchen.getExperiment( 'my-awesome-experiment' );
 *
 * // Is the current user assigned A or B for the "My Awesome Experiment" experiment?
 * if ( e.isAssignedGroup( 'A', 'B' ) {
 *   // ...
 * }
 *
 * @method isAssignedGroup
 * @instance
 * @memberof mw.testKitchen.ExperimentInterface
 *
 * @param {...string} groups
 * @return {boolean}
 */

/**
 * Sends an analytics event related to the experiment.
 *
 * If the user is enrolled in the experiment, then the event is decorated with
 * experiment-related data and sent. The experiment-related data are specified and documented in
 * [the `fragment/analytics/product_metrics/experiment` schema fragment][0].
 *
 * By default, the analytics event will be sent to the `product_metrics.web_base` stream and be
 * validated with the `/analytics/product_metrics/web/base/2.0.0` schema. The stream and schema
 * can be overridden with {@link mw.testKitchen.ExperimentInterface#setStream} and
 * {@link mw.testKitchen.ExperimentInterface#setSchema},
 * respectively.
 *
 * Per-event contextual attributes can be passed as contextualAttributes. In this case, they will
 * be added to the events along with the ones that are defined in the experiment config
 *
 *
 * [0]: https://gitlab.wikimedia.org/repos/data-engineering/schemas-event-secondary/-/blob/master/jsonschema/fragment/analytics/product_metrics/experiment/current.yaml?ref_type=heads
 *
 * @method send
 * @instance
 * @memberof mw.testKitchen.ExperimentInterface
 *
 * @param {string} action The action that the user enrolled in this experiment took, e.g.
 *  "hover", "click"
 * @param {Object} [interactionData] Additional data about the action that the user enrolled in
 *  the experiment took
 * @param {string[]} [contextualAttributes] Per-event contextual attributes
 */

/**
 * Submits an event related to this experiment.
 *
 * This method makes `Experiment` compatible with [the click-through rate implementation in the
 * `ext.wikimediaEvents.testKitchen` ResourceLoader module][0] by proxying to
 * {@link mw.testKitchen.ExperimentInterface#send}. Calling this outside of Test Kitchen is not
 * supported.
 *
 * [0]: https://gerrit.wikimedia.org/r/plugins/gitiles/mediawiki/extensions/WikimediaEvents/+/master/modules/ext.wikimediaEvents.testKitchen/ClickThroughRateInstrument.js
 *
 * @see https://phabricator.wikimedia.org/T394675
 *
 * @package
 *
 * @method submitInteraction
 * @instance
 * @memberof mw.testKitchen.ExperimentInterface
 *
 * @param {string} action The action related to the submitted event
 * @param {Object} [interactionData] Additional data
 * @param {string[]} [contextualAttributes] Per-event contextual attributes
 */

/**
 * Sends an exposure event for this experiment with {@link mw.testKitchen.ExperimentInterface#send}.
 *
 * The exposure event will always have:
 *
 * 1. `action=experiment_exposure`
 * 2. The following contextual attributes:
 *    * `performer_is_logged_in`
 *    * `performer_is_temp`
 *    * `performer_is_bot`
 *    * `mediawiki_database`
 *
 * @method sendExposure
 * @instance
 * @memberof mw.testKitchen.ExperimentInterface
 */

/**
 * Sets the stream to send analytics events to with {@link mw.testKitchen.ExperimentInterface#send}.
 *
 * This method is chainable.
 *
 * @method setStream
 * @instance
 * @memberof mw.testKitchen.ExperimentInterface
 * @deprecated
 *
 * @param {string} streamName
 * @return {mw.testKitchen.ExperimentInterface} The instance on which this method was called
 */

/**
 * Sets the ID of the schema used to validate analytics events sent with
 * {@link mw.testKitchen.ExperimentInterface#send}.
 *
 * This method is chainable.
 *
 * @method setSchema
 * @instance
 * @memberof mw.testKitchen.ExperimentInterface
 *
 * @param {string} schemaID
 * @return {mw.testKitchen.ExperimentInterface}
 */

// ---

/**
 * @typedef {Object} mw.testKitchen.InstrumentSamplingConfig
 * @property {string} unit
 * @property {number} rate
 *
 * @package
 */

/**
 * @typedef {Object} mw.testKitchen.PartialInstrumentConfig
 * @property {mw.testKitchen.InstrumentSamplingConfig} sample
 * @property {string} stream_name The name of the stream to send experiment-related analytics
 *  events to
 * @property {mw.testKitchen.ContextualAttribute[]} contextual_attributes
 */

/**
 * @typedef {mw.testKitchen.PartialInstrumentConfig} mw.testKitchen.InstrumentConfig
 * @property {string} schema_id The ID of the schema used to validate experiment-related analytics
 *
 * @package
 */

// ---

/**
 * @interface InstrumentInterface
 * @memberof mw.testKitchen
 */

/**
 * Sends an analytics event.
 *
 * By default, the analytics event will be validated with the
 * `/analytics/product_metrics/web/base/2.0.0` schema. The schema can be overridden with
 * {@link mw.testKitchen.InstrumentInterface#setSchema}.
 *
 * @method send
 * @instance
 * @memberof mw.testKitchen.InstrumentInterface
 *
 * @param {string} action The action that the user enrolled in this experiment took, e.g.
 *  "hover", "click"
 * @param {Object} [interactionData] Additional data
 */

/**
 * Sends an analytics event.
 *
 * This method makes `mw.testKitchen.InstrumentInterface` compatible with
 * [the click-through rate implementation in the `ext.wikimediaEvents.testKitchen` ResourceLoader
 * module][0] by proxying to {@link mw.testKitchen.InstrumentInterface#send}. Calling this outside
 * of Test Kitchen is not supported.
 *
 * [0]: https://gerrit.wikimedia.org/r/plugins/gitiles/mediawiki/extensions/WikimediaEvents/+/master/modules/ext.wikimediaEvents.testKitchen/ClickThroughRateInstrument.js
 *
 * @see https://phabricator.wikimedia.org/T394675
 *
 * @package
 *
 * @method submitInteraction
 * @instance
 * @memberof mw.testKitchen.InstrumentInterface
 *
 * @param {string} action The action related to the submitted event
 * @param {Object} [interactionData] Additional data
 */

/**
 * Sends an analytics event immediately.
 *
 * This method sends an event right away via the [Navigator: sendBeacon() method][0]
 *
 * [0]: https://developer.mozilla.org/en-US/docs/Web/API/Navigator/sendBeacon
 *
 * @package
 *
 * @method sendImmediately
 * @instance
 * @memberof mw.testKitchen.InstrumentInterface
 *
 * @param {string} action The action related to the submitted event
 * @param {Object} [interactionData] Additional data
 */

/**
 * Sets the ID of the schema used to validate analytics events sent with
 * {@link mw.testKitchen.InstrumentInterface#send}.
 *
 * This method is chainable.
 *
 * @method setSchema
 * @instance
 * @memberof mw.testKitchen.InstrumentInterface
 *
 * @param {string} schemaID
 * @return {mw.testKitchen.InstrumentInterface}
 */

/**
 * Gets whether the instrument is in-sample.
 *
 * @method isInSample
 * @instance
 * @memberof mw.testKitchen.InstrumentInterface
 *
 * @return {boolean}
 */

// ---

/**
 * @typedef {Object} mw.testKitchen.TestEvent
 * @property {string} action
 * @property {Object} interactionData
 * @property {string[]} [contextualAttributes]
 */

// ---

/**
 * @interface mw.testKitchen.StubbedExperimentInterface
 * @extends mw.testKitchen.ExperimentInterface
 */

/**
 * The events that have been sent for the experiment.
 *
 * @constant {mw.testKitchen.TestEvent[]} events
 * @instance
 * @memberof mw.testKitchen.StubbedExperimentInterface
 */

/**
 * The number of events that have been sent for the experiment.
 *
 * @constant {number} eventCount
 * @instance
 * @memberof mw.testKitchen.StubbedExperimentInterface
 */

// ---

/**
 * @interface FakeExperimentsHelper
 * @memberof mw.testKitchen
 */

/**
 * Restores {@link mw.testKitchen.getExperiment} to its original state.
 *
 * This method should be called after every unit test that calls
 * {@link mw.testKitchen.useFakeExperiments}.
 *
 * @method restore
 * @instance
 * @memberof mw.testKitchen.FakeExperimentsHelper
 */

/**
 * Stubs enrollment in an experiment.
 *
 * @example
 * const tk = mw.testKitchen.useFakeExperiments();
 * const e = tk.stubExperiment( 'my-awesome-experiment', 'treatment' );
 *
 * // Run Code Under Test
 *
 * assert.strictEqual( e.eventCount, 1 );
 * assert.strictEqual( e.events[ 0 ].action, 'my-awesome-action' );
 *
 * assert.strictEqual( tk.globalEventCount, 1 );
 *
 * @method stubExperiment
 * @instance
 * @memberof mw.testKitchen.FakeExperimentsHelper
 *
 * @param {string} experimentName
 * @param {string} assigned
 * @return {mw.testKitchen.StubbedExperimentInterface}
 */

/**
 * The number of events that have been sent by all stubbed experiments.
 *
 * @constant {number} mw.testKitchen.FakeExperimentsHelper#globalEventCount
 */

// ---

/**
 * @interface mw.testKitchen.StubbedInstrumentInterface
 * @extends mw.testKitchen.InstrumentInterface
 */

/**
 * The events that have been sent for the experiment.
 *
 * @constant {mw.testKitchen.TestEvent[]} events
 * @instance
 * @memberof mw.testKitchen.StubbedInstrumentInterface
 */

/**
 * The number of events that have been sent for the experiment.
 *
 * @constant {number} eventCount
 * @instance
 * @memberof mw.testKitchen.StubbedInstrumentInterface
 */

// ---

/**
 * @interface FakeInstrumentsHelper
 * @memberof mw.testKitchen
 */

/**
 * Restores {@link mw.testKitchen.getInstrument} to its original state.
 *
 * This method should be called after every unit test that calls
 * {@link mw.testKitchen.useFakeInstruments}.
 *
 * @method restore
 * @instance
 * @memberof mw.testKitchen.FakeInstrumentsHelper
 */

/**
 * Stubs an instrument.
 *
 * @example
 * const tk = mw.testKitchen.useFakeExperiments();
 * const e = tk.stubInstrument( 'my-awesome-instrument' );
 *
 * // Run Code Under Test
 *
 * assert.strictEqual( e.eventCount, 1 );
 * assert.strictEqual( e.events[ 0 ].action, 'my-awesome-action' );
 *
 * assert.strictEqual( tk.globalEventCount, 1 );
 *
 * @method stubInstrument
 * @instance
 * @memberof mw.testKitchen.FakeInstrumentsHelper
 *
 * @param {string} instrumentName
 * @return {mw.testKitchen.StubbedInstrumentInterface}
 */

/**
 * The number of events that have been sent by all stubbed experiments.
 *
 * @constant {number} mw.testKitchen.FakeInstrumentsHelper#globalEventCount
 */
