/**
 * @typedef {string} mw.testKitchen.ContextualAttribute
 *
 * @package
 */

// ---

/**
 * @interface EventSenderInterface
 * @memberof mw.testKitchen
 */

/**
 * Sends the event to the URL using [the Beacon API][0].
 *
 * By default, the event is added to a queue, which is then drained after 5 seconds or if the
 * page is hidden, e.g. when the user switches to another tab. If the page is unloading,
 * however, the event will be sent immediately.
 *
 * When the queue is drained, events are grouped by URL and then those groups of events are sent
 * in a single beacon request to that URL.
 *
 * [0]: https://developer.mozilla.org/en-US/docs/Web/API/Beacon_API
 *
 * @method sendEvent
 * @instance
 * @memberof mw.testKitchen.EventSenderInterface
 *
 * @param {Object} event
 * @param {string} url
 */

// ---

// The relationship between PartialExperimentConfig and ExperimentConfig is different from
// that of PartialInstrumentConfig and InstrumentConfig. Currently, PartialExperimentConfig objects
// are looked up by stream name rather than experiment name. The relationship between the types
// reflects this.

/**
 * A partial configuration for an experiment, which was generated by
 * `\MediaWiki\Extension\TestKitchen\ResourceLoader\Hooks::getExperimentConfigs()`. This can be
 * removed as part of T408186.
 *
 * @typedef {Object} mw.testKitchen.PartialExperimentConfig
 * @property {mw.testKitchen.ContextualAttribute[]} contextual_attributes
 *
 * @package
 */

/**
 * @typedef {Object} mw.testKitchen.ExperimentConfig
 * @property {string} enrolled The machine-readable name of the experiment
 * @property {string} assigned The group assigned to the user
 * @property {string} subject_id The ID assigned to the user when they were enrolled in the
 *  experiment
 * @property {string} sampling_unit The sampling unit used to determine whether the user should
 *  be enrolled in the experiment
 * @property {string} coordinator The name of the system that coordinated the enrollment of the
 *  user in the experiment. This parameter is used as the value for the `experiment.coordinator`
 *  field in all experiment-related analytics events, so it should be one of `default`, `custom`, or
 *  `forced`
 * @property {string} stream_name The name of the stream to send experiment-related analytics
 *  events to
 * @property {string} schema_id The ID of the schema used to validate experiment-related analytics
 *  events with
 * @property {mw.testKitchen.ContextualAttribute[]} contextual_attributes
 *
 * @package
 */

// ---

/**
 * @interface ExperimentInterface
 * @memberof mw.testKitchen
 */

/**
 * Gets the group assigned to the user when they were enrolled in the experiment.
 *
 * @method getAssignedGroup
 * @instance
 * @memberof mw.testKitchen.ExperimentInterface
 *
 * @return {string|null}
 */

/**
 * Gets whether the group assigned to the current user is one of the given groups.
 *
 * @see mw.testKitchen.ExperimentInterface#getAssignedGroup
 *
 * @example
 * const e = mw.testKitchen.getExperiment( 'my-awesome-experiment' );
 *
 * // Is the current user assigned A or B for the "My Awesome Experiment" experiment?
 * if ( e.isAssignedGroup( 'A', 'B' ) {
 *   // ...
 * }
 *
 * @method isAssignedGroup
 * @instance
 * @memberof mw.testKitchen.ExperimentInterface
 *
 * @param {...string} groups
 * @return {boolean}
 */

/**
 * Sends an analytics event related to the experiment.
 *
 * If the user is enrolled in the experiment, then the event is decorated with
 * experiment-related data and sent. The experiment-related data are specified and documented in
 * [the `fragment/analytics/product_metrics/experiment` schema fragment][0].
 *
 * By default, the analytics event will be sent to the `product_metrics.web_base` stream and be
 * validated with the `/analytics/product_metrics/web/base/2.0.0` schema. The stream and schema
 * can be overridden with {@link mw.testKitchen.ExperimentInterface#setStream} and
 * {@link mw.testKitchen.ExperimentInterface#setSchema},
 * respectively.
 *
 * [0]: https://gitlab.wikimedia.org/repos/data-engineering/schemas-event-secondary/-/blob/master/jsonschema/fragment/analytics/product_metrics/experiment/current.yaml?ref_type=heads
 *
 * @method send
 * @instance
 * @memberof mw.testKitchen.ExperimentInterface
 *
 * @param {string} action The action that the user enrolled in this experiment took, e.g.
 *  "hover", "click"
 * @param {Object} [interactionData] Additional data about the action that the user enrolled in
 *  the experiment took
 */

/**
 * Submits an event related to this experiment.
 *
 * This method makes `Experiment` compatible with [the click-through rate implementation in the
 * `ext.wikimediaEvents.testKitchen` ResourceLoader module][0] by proxying to
 * {@link mw.testKitchen.ExperimentInterface#send}. Calling this outside of Test Kitchen is not
 * supported.
 *
 * [0]: https://gerrit.wikimedia.org/r/plugins/gitiles/mediawiki/extensions/WikimediaEvents/+/master/modules/ext.wikimediaEvents.testKitchen/ClickThroughRateInstrument.js
 *
 * @see https://phabricator.wikimedia.org/T394675
 *
 * @package
 *
 * @method submitInteraction
 * @instance
 * @memberof mw.testKitchen.ExperimentInterface
 *
 * @param {string} action The action related to the submitted event
 * @param {Object} interactionData Additional data
 */

/**
 * Sends an exposure event for this experiment with {@link mw.testKitchen.ExperimentInterface#send}.
 *
 * The exposure event will always have:
 *
 * 1. `action=experiment_exposure`
 * 2. The following contextual attributes:
 *    * `performer_is_logged_in`
 *    * `performer_is_temp`
 *    * `performer_is_bot`
 *    * `mediawiki_database`
 *
 * @method sendExposure
 * @instance
 * @memberof mw.testKitchen.ExperimentInterface
 */

/**
 * Sets the stream to send analytics events to with {@link mw.testKitchen.ExperimentInterface#send}.
 *
 * This method is chainable.
 *
 * @method setStream
 * @instance
 * @memberof mw.testKitchen.ExperimentInterface
 *
 * @param {string} streamName
 * @return {mw.testKitchen.ExperimentInterface} The instance on which this method was called
 */

/**
 * Sets the ID of the schema used to validate analytics events sent with
 * {@link mw.testKitchen.ExperimentInterface#send}.
 *
 * This method is chainable.
 *
 * @method setSchema
 * @instance
 * @memberof mw.testKitchen.ExperimentInterface
 *
 * @param {string} schemaID
 * @return {mw.testKitchen.ExperimentInterface}
 */

// ---

/**
 * @typedef {Object} mw.testKitchen.InstrumentSamplingConfig
 * @property {string} unit
 * @property {number} rate
 *
 * @package
 */

/**
 * @typedef {Object} mw.testKitchen.PartialInstrumentConfig
 * @property {mw.testKitchen.InstrumentSamplingConfig} sample
 * @property {string} stream_name The name of the stream to send experiment-related analytics
 *  events to
 * @property {mw.testKitchen.ContextualAttribute[]} contextual_attributes
 */

/**
 * @typedef {mw.testKitchen.PartialInstrumentConfig} mw.testKitchen.InstrumentConfig
 * @property {string} schema_id The ID of the schema used to validate experiment-related analytics
 *
 * @package
 */

// ---

/**
 * @interface InstrumentInterface
 * @memberof mw.testKitchen
 */

/**
 * Sends an analytics event.
 *
 * By default, the analytics event will be validated with the
 * `/analytics/product_metrics/web/base/2.0.0` schema. The schema can be overridden with
 * {@link mw.testKitchen.InstrumentInterface#setSchema}.
 *
 * @method send
 * @instance
 * @memberof mw.testKitchen.InstrumentInterface
 *
 * @param {string} action The action that the user enrolled in this experiment took, e.g.
 *  "hover", "click"
 * @param {Object} [interactionData] Additional data about the action that the user enrolled in
 *  the experiment took
 */

/**
 * Sends an analytics event.
 *
 * This method makes `mw.testKitchen.InstrumentInterface` compatible with
 * [the click-through rate implementation in the `ext.wikimediaEvents.testKitchen` ResourceLoader
 * module][0] by proxying to {@link mw.testKitchen.InstrumentInterface#send}. Calling this outside
 * of Test Kitchen is not supported.
 *
 * [0]: https://gerrit.wikimedia.org/r/plugins/gitiles/mediawiki/extensions/WikimediaEvents/+/master/modules/ext.wikimediaEvents.testKitchen/ClickThroughRateInstrument.js
 *
 * @see https://phabricator.wikimedia.org/T394675
 *
 * @package
 *
 * @method submitInteraction
 * @instance
 * @memberof mw.testKitchen.InstrumentInterface
 *
 * @param {string} action The action related to the submitted event
 * @param {Object} interactionData Additional data
 */

/**
 * Sets the ID of the schema used to validate analytics events sent with
 * {@link mw.testKitchen.InstrumentInterface#send}.
 *
 * This method is chainable.
 *
 * @method setSchema
 * @instance
 * @memberof mw.testKitchen.InstrumentInterface
 *
 * @param {string} schemaID
 * @return {mw.testKitchen.InstrumentInterface}
 */

/**
 * Sets the ID of the schema used to validate analytics events sent with
 * {@link mw.testKitchen.InstrumentInterface#send}.
 *
 * This method is provided for backwards compatibility with [existing instrumentation][0].
 *
 * This method is chainable.
 *
 * [0]: https://codesearch.wmcloud.org/things/?q=%5C.setSchemaID%5C%28&files=&excludeFiles=modules%5C%2Flib%5C%2F&repos=
 *
 * @deprecated
 *
 * @method setSchemaID
 * @instance
 * @memberof mw.testKitchen.InstrumentInterface
 *
 * @param {string} schemaID
 * @return {mw.testKitchen.InstrumentInterface}
 */

/**
 * Gets whether the instrument is in-sample.
 *
 * @method isInSample
 * @instance
 * @memberof mw.testKitchen.InstrumentInterface
 *
 * @return {boolean}
 */

/**
 * Gets whether the instrument is in-sample.
 *
 * This method is provided for backwards compatibility with [existing instrumentation][0].
 *
 * [0]: https://codesearch.wmcloud.org/things/?q=%5C.isStreamInSample%5C%28&files=js%24&excludeFiles=modules%5C%2Flib%5C%2F&repos=
 *
 * @deprecated
 *
 * @method isStreamInSample
 * @instance
 * @memberof mw.testKitchen.InstrumentInterface
 *
 * @return {boolean}
 */

/**
 * Gets whether the instrument is enabled, i.e. whether the instrument is in-sample.
 *
 * This method is provided for backwards compatibility with [existing instrumentation][0].
 *
 * [0]: https://codesearch.wmcloud.org/things/?q=getInstrument%5C%28&files=js%24&excludeFiles=modules%5C%2Flib%5C%2F&repos=
 *
 * @deprecated
 *
 * @method isEnabled
 * @instance
 * @memberof mw.testKitchen.InstrumentInterface
 *
 * @return {boolean}
 */
